using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DielershipLibrary.CarModelsLists
{
    public class CarsModelsLists
    {
        public static readonly object[] AudiModels = new object[] {
            "A3" ,"S3", "RS3",
            "A4", "S4","RS4",
            "A5", "S5" , "RS5",
            "A6", "S6" , "RS6",
            "Allroad",
            "A7" , "S7", "RS7",
            "A8" , "S8",
            "Q2" ,"Q3" , "RS", "Q3",
            "Q5" , "SQ5",
            "Q7" , "SQ7",
            "Q8"  ,"Quattro", "Coupe GT",
            "R8", "R8 GT",
            "TT","TTS", "TT RS"};

        public static readonly object[] BMWModels = new object[] {
            "1 Series",
            "3 series",
            "5 Series" ,
            "M1",
            "M3",
            "M5",
            "6 Series",
            "M6",
            "7 Series",
            "8 Series",
            "BMW i8",
            "BMW i3",
            "BMW E9",
            "X5 M",
            "X5",
            "X3"
        };

        public static readonly object[] FordModels = new object[] {
            "P7",
            "C-Max",
            "Capri",
            "Cougar",
            "Eifel",
            "Escort",
            "Fiesta",
            "Focus",
            "Fusion",
            "Granada",
            "Köln",
            "Kuga",
            "Puma",
            "Rheinland",
            "Taunus"
        };

        public static readonly object[] MercedesModels = new object[] {
            "A",
            "A 140",
            "A 150",
            "A 160",
            "A 170",
            "A 180",
            "A 190",
            "A 200",
            "A 210",
            "A 220",
            "A45 AMG",
            "B",
            "B 150",
            "B 170",
            "B 180",
            "B 200",
            "C",
            "C 180",
            "C 200",
            "C 220",
            "C 230",
            "C 250",
            "C 280",
            "C 300",
            "C 30 AMG",
            "C 32 AMG",
            "C 320",
            "C 350",
            "C 36 AMG",
            "C 400",
            "C 43 AMG",
            "C 450 AMG",
            "C 55 AMG",
            "C 63 AMG",
            "CL",
            "CL 230",
            "CL 320",
            "CL 420",
            "CL 500",
            "CL 55 AMG",
            "CL 600",
            "CL 63 AMG",
            "CL 65 AMG",
            "CLA",
            "CLA 180",
            "CLA 200",
            "CLA 220",
            "CLA 250",
            "CLA 45 AMG",
            "CLC",
            "CLC 160",
            "CLC 180",
            "CLC 200",
            "CLC 220",
            "CLC 230",
            "CLC 250",
            "CLC 350",
            "CLK",
            "CLK 55 AMG",
            "CLK 63 AMG",
            "CLK-GTR",
            "CLS 250",
            "CLS 300",
            "CLS 320",
            "CLS 350",
            "CLS 500",
            "CLS 55",
            "CLS 55 AMG",
            "CLS 63",
            "CLS 63 AMG",
            "E 200",
            "E 220",
            "E 230",
            "E 240",
            "E 250",
            "E 260",
            "E 270",
            "E 280",
            "E 290",
            "E 300",
            "E 320",
            "E 350",
            "E 36 AMG",
            "E 400",
            "E 420",
            "E 43 AMG",
            "E 430",
            "E 500",
            "E 55 AMG",
            "E 60",
            "E 60 AMG",
            "E 63 AMG",
            "GLA 180",
            "GLA 200",
            "GLA 220",
            "GLA 250",
            "GLA 45 AMG",
            "R",
            "R 280",
            "R 300",
            "R 320",
            "R 350",
            "R 500",
            "R 63 AMG",
            "S",
            "S 320",
            "S 350",
            "S 350",
            "S 400",
            "S 450",
            "S 400",
            "S 500",
            "S 500",
            "S 560",
            "S 500",
            "S 500",
            "S 600",
            "S 63 AMG",
            "S 65 AMG",
            "G",
            "GL",
            "GLK",
            "G-Class",
            "M-Class",
            "ML-Class",
            "R-Class",
            "S-Class",
            "SL",
            "SLK",
            "SLR McLaren",
            "SLS",
            "V-Class",
        };

        public static readonly object[] OpelModels = new object[] {
            "Adam",
            "Agila",
            "Astra",
            "Calibra",
            "Cascada",
            "Chevette",
            "Combo",
            "Corsa",
            "Frontera",
            "GT",
            "Insignia",
            "Manta",
            "Meriva",
            "Mokka",
            "Monterey",
            "Monza",
            "Movano",
            "Olympia",
            "Olympia Rekord",
            "Omega",
            "Signum",
            "Speedster",
            "Tigra",
            "Tigra TwinTop",
            "Vectra",
            "Vivaro",
            "Zafira",
            "Zafira Tourer"
        };

        public static readonly object[] PorscheModels = new object[] {
            "356",
            "911 / 912 / 930",
            "914",
            "924",
            "928",
            "944",
            "959",
            "968",
            "918 Spyder",
            "Boxster",
            "Carrera GT",
            "Cayenne",
            "Cayman",
            "Panamera",
            "Macan"
        };

        public static readonly object[] VolkswagenModels = new object[] {
            "Amarok",
            "Beetle",
            "Caddy",
            "Corrado",
            "Dasher",
            "Eos",
            "Fox",
            "Golf",
            "Golf Plus",
            "Jetta / Bora / Vento",
            "Karmann Ghia",
            "Lupo",
            "New Beetle",
            "Passat",
            "Phaeton",
            "Polo",
            "Scirocco",
            "Sharan",
            "SP2",
            "Tiguan",
            "Touareg",
            "Touran",
            "Transporter / Caravelle / Microbus / Vanagon / Eurovan",
        };

        public static readonly object[] CitroenModels = new object[] {
            "C2",
            "C3",
            "C4",
            "C4 Picasso",
            "C4 Grand Picasso",
            "C4 Aircross",
            "C4 Cactus",
            "C5",
            "C6",
            "C8",
            "Saxo",
            "Synergie",
            "Xsara",
            "Xsara Picasso",
            "C-Crosser",
            "Berlingo",
            "Elysee",
            "Nemo",
            "Jumper",
            "Jumpy",
        };

        public static readonly object[] PeugeotModels = new object[] {
        "108" ,
        "206",
        "207",
        "208" ,
        "208 GTI",
        "301" ,
        "306",
        "307",
        "308" ,
        "308 GTI",
        "406",
        "407",
        "408" ,
        "508" ,
        "2008",
        "3008",
        "4007",
        "5008",
        "Bipper",
        "Partner",
        "Expert",
        "Boxer"
        };

        public static readonly object[] AlfaRomeoModels = new object[] {
           "MiTo",
           "Giulietta",
           "4C",
           "4C",
           "Spider",
           "Giulia",
           "Stelvio",
           "Giulia",
           "Alfetta",
           "Giulietta",
           "156",
           "166",
           "159",
           "Giulia"
        };

        public static readonly object[] FiatModels = new object[] {
             "Punto",
             "Panda",
             "500",
             "Linea",
             "Bravo",
             "Sedic",
             "Albea",
             "Idea",
             "Freemont"
        };
        public static readonly object[] FerrariModels = new object[] {
           "488",
           "GTB",
           "488",
           "Spider",
           "Portofino",
           "812",
           "Superfast",
           "F12tdf",
           "GTC4Lusso / GTC4Lusso T",
           "LaFerrari",
           "LaFerrari Aperta",
        };

        public static readonly object[] HondaModels = new object[] {
           "Accord",
           "Amaze",
           "Avancier",
           "Ballade",
           "Brio",
           "BR-V",
           "City",
           "Civic",
           "Civic Tourer",
           "Civic Type R",
           "Clarity",
           "Crider",
           "CR-V",
           "CR-V S",
           "Crosstour",
           "Elysion",
           "Fit/Jazz",
           "Fit Hybrid",
           "Fit Shuttle",
           "Hobio",
           "HR-V",
           "FR-V",
           "Jazz",
           "Jazz RS",
           "Legend",
           "Odyssey/Shuttle",
           "Shuttle",
        };

        public static readonly object[] AcuraModels = new object[] {
           "CDX",
           "ILX",
           "MDX",
           "NSX",
           "RDX",
           "RLX",
           "TLX",
           "CSX",
           "EL",
           "Integra",
           "RSX",
           "NSX",
           "CL",
           "RL",
           "ZDX",
           "TL",
           "TSX",
        };

        public static readonly object[] MazdaModels = new object[] {
            "2",
            "3",
            "6",
            "MX-3",
            "MX-5/Roadster",
            "CX-3",
            "CX-4",
            "CX-5",
            "CX-8",
            "CX-9",
            "BT-50",
            "Titan",
        };

        public static readonly object[] MitsubishiModels = new object[] {
            "Colt",
            "Galant",
            "Grandis",
            "Endeavor",
            "Raider",
            "Eclipse",
            "Eclipse Spyder",
            "Lancer",
            "Sigma",
            "Starion",
            "3000 GT",
            "Space Runner",
            "L300",
            "Colt CZC",
            "Carisma",
            "Galant",
            "Eclipse",
            "Mirage",
            "i-MiEV",
            "Outlander Airtrek",
            "Mirage G4",
            "Outlander Sport",
            "L 200",
            "Pajero",
            "Lancer",
            "Pajero Pinin",
        };

        public static readonly object[] NissanModels = new object[] {
            "Almera",
            "Patrol",
            "Skyline",
            "Caravan",
            "Pulsar",
            "Maxima",
            "Prairie",
            "AD",
            "Atlas",
            "Micra",
            "Sentra",
            "Urvan",
            "Pathfinder",
            "Cima",
            "Serena",
            "Altima",
            "Cube",
            "Elgrand",
            "Navara",
            "Sylphy",
            "X-Trail",
            "Murano",
            "Teana",
            "Armada",
            "Primera",
            "Fuga",
            "Lafesta",
            "Titan",
            "Note",
            "Livina",
            "Clipper",
            "Latio",
            "Qashqai",
            "Rogue",
            "Versa",
            "GT-R",
            "370Z",
            "Leaf",
            "NV200",
            "Juke",
            "NV400",
            "NV",
            "NV100",
            "NV350",
            "Dayz",
            "Dayz Roox",
            "NV300",
            "Kicks"
        };

        public static readonly object[] InfinityModels = new object[] {
            "Q30",
            "Q50",
            "Q60",
            "Q70",
            "QX30",
            "QX50",
            "QX60",
            "QX80",
            "M30",
            "QX4",
            "J30",
            "I30",
            "Q40",
            "Q45",
            "ESQ",
            "QX70"
        };

        public static readonly object[] SubaruModels = new object[] {
            "Impreza",
            "Legacy",
            "Forester",
            "Outback",
            "WRX",
            "BRZ",
            "GTB"

        };

        public static readonly object[] ToyotaModels = new object[] {
            "Aygo",
            "Allion",
            "Aurion",
            "Crown",
            "Etios",
            "iQ",
            "ist",
            "Mark X",
            "Auris",
            "Avalon",
            "Belta",
            "Camry",
            "Corolla",
            "Vios",
            "Wigo",
            "Yaris",
            "FT-1",
            "Fortuner",
            "Rush",
            "Highlander",
            "Land cruiser",
            "Prado",
            "Rav4",
            "Tundra",
            "Venuza",
            "Sequoia",
            "Yaris Verso",
            "Avensis Verso"
        };

        public static readonly object[] HyundaiModels = new object[]
        {
            "Elantra",
            "i20",
            "Eon",
            "Grand i10",
            "i10",
            "Verna",
            "Santa Fe",
            "Santro",
            "Sonata",
            "Terracan",
            "ix30",
            "Tucson",
            "Accent",
            "Entourage",
            "Grandeur",
            "Genesis",
            "Genesis Coupe",
            "Veracruz",
            "Equus",
            "Getz",
            "Lavita",
            "Coupe",
            "Trajet",

        };
        public static readonly object[] KiaModels = new object[]
       {
            "Cadenza",
            "Cee'd",
            "Cerato",
            "Forte Koup",
            "Quoris",
            "Magentis/",
            "Picanto",
            "Ray",
            "Rio",
            "Soul",
            "Stinger",
            "Stonic",
            "Carens",
            "Carnival",
            "Mohave",
            "Sorento",
            "Sportage",
            "Pregio",
            "Soul",
            "Niro"
       };

        public static readonly object[] DaciaModels = new object[]
      {
        "Logan",
        "Sandero",
        "Sandero Stepway",
        "Duster",
        "Lodgy",
        "Lodgy Stepway",
        "Dokker",
        "Dokker Van",
        "Dokker Stepway",
      };

        public static readonly object[] VolvoModels = new object[]
     {
         "S40",
         "V40",
          "S70",
          "V70",
          "S90",
          "V90",
          "C70 coupe",
          "V70 XC",
          "C70",
          "S80",
          "S60",
          "V70",
          "V70 XC",
          "XC90",
          "V50",
          "C30",
          "XC60",
          "S90",
     };


        public static readonly object[] AstonMartinModels = new object[]
     {
            "V8 Coupe/V8 Volante",
            "DB7 / Vantage",
            "V12 Vanquish/ S",
            "DB7 Zagato",
            "DB AR1",
            "DB9",
            "V8 and V12 Vantage",
            "DBS V12",
            "One-77",
            "Rapide / S",
            "Virage/Virage Volante",
            "Cygnet",
            "V12 Zagato",
            "Vanquish / Volante",
            "DB11"
     };

        public static readonly object[] BentleyModels = new object[]
     {
         "Flying Spur",
         "Bentayga",
         "Continental GT",
         "Mulsanne",
         "Continental GTC"
     };

        public static readonly object[] JaguarModels = new object[]
      {
            "F-Type",
            "XE",
            "XF",
            "XJ",
            "R"

      };

        public static readonly object[] LandRoverModels = new object[]
      {
        "Discovery Sport",
        "Discovery 5 Large",
        "Range Rover Evoque",
        "Range Rover Velar",
        "Range Rover Sport",
        "Range Rover",
      };

        public static readonly object[] MiniModels = new object[]
     {
         "One",
         "One D",
         "Hatch",
         "Convertable",
         "Clubman",
         "Convertible/Hardtop",
         "Countryman",
         "Coupe",
         "Roadster",
         "Paceman",
         "First",
         "Cooper",
         "Cooper D",
         "Cooper SD",
         "Cooper S",
         "E",
         "John Cooper Works"
     };

        public static readonly object[] GreatWallModels = new object[]
    {
       "Volex",
       "Hover",
       "Hover H3",
       "Hover H5",
       "Hover H6"

    };

        public static readonly object[] RenaultModels = new object[]
    {
        "Alaskan",
        "Captur",
        "Clio",
        "Duster",
        "Espace",
        "Fluence",
        "Kadjar",
        "Kangoo",
        "Koleos",
        "Kwid",
        "Megane",
        "Pulse",
        "Safrane",
        "Scala",
        "Scenic",
        "Symbol",
        "Talisman",
        "Twingo",
        "Twizy",
        "Zoe",
        "Duster",
        "Logan",
        "Sandero",
        "Lodgy",
        "Latitude",
    };

        public static readonly object[] BugattiModels = new object[]
    {
        "Veyron",
        "Chiron",
    };

        public static readonly object[] SmartModels = new object[]
    {
        "ForTwo",
        "ForFour",
        "Roadster",
        "Crossblade",
        "City"
    };

        public static readonly object[] LexusModels = new object[]
    {
        "IS200",
        "IS200d",
        "IS220d",
        "IS250",
        "IS300",
        "IS350",
        "IS F",
        "GX",
        "RC",
        "CT",
        "HS",
        "RX",
        "ES 250",
        "ES 300",
        "ES 300",
        "ES 330",
        "ES 350",
        "ES 240",
        "ES 250",
        "ES 300h",
        "ES 350",
        "ES 200",
        "ES 250",
        "ES 300h",
        "ES 350",
        "GS 300",
        "GS 300",
        "GS 400",
        "GS 430",
        "GS 300",
        "GS 300 AWD",
        "GS 430",
        "GS 450h",
        "GS 35",
        "GS 350 AWD",
        "GS 460",
        "GS 250",
        "GS 350",
        "GS 350 AWD",
        "GS 450h",
        "GS 200t",
        "GS 250",
        "GS 350",
        "GS 350 AWD",
        "GS 450h",
        "GS F",
        "LS 400",
        "LS 430",
        "LS 460",
        "LS 460L",
        "LS 600h",
        "LS 600hL",
        "LS 460",
        "LS 460 AWD",
        "LS 460L",
        "LS 460L AWD",
        "LS 460SZ",
        "LS 460",
        "LS 460 AWD",
        "LS 460L",
        "LS 460L AWD",
        "LS 600hL",
        "LS 500",
        "LS 500h",

    };


        public static readonly object[] SsangYongModels = new object[]
    {
        "Tivoli",
        "Actyon",
        "Rexton",
        "Korando",
        "Actyon Sports",
        "Rodius/Stavic",
        "Chairman W",
        "Kyron",
        "Musso",
    };

        public static readonly object[] DodgeModels = new object[]
   {
        "Challenger",
        "Charger",
        "Durango",
        "Grand Caravan",
        "Journey",
        "Neon",
        "Viper",
        "Ram",
        "Sprinter",
        "SRT-4",
        "Stratus",
        "Nitro",
        "Dart",
        "Dakota",
        "Caliber",
        "Avenger"
   };

        public static readonly object[] ChryslerModels = new object[]
   {
       "Voyager",
       "Sebring",
       "PT Cruiser",
       "Delta",
       "Crossfire",
       "Aspen",
       "200",
       "300M",
       "300C",
       "Ypsilon"
   };

        public static readonly object[] JeepModels = new object[]
   {
       "Cherokee",
       "Grand Cherokee",
       "Gladiator",
       "Wrangler",
       "Commander",
       "Compass",
   };
        public static readonly object[] CadillacModels = new object[]
   {
        "Escalade",
        "Escalade ESV",
        "CTS",
        "CTS-V",
        "CTS-V",
        "ATS",
        "ATS-V",
        "XTS",
        "CT6",
        "XT5"
   };
        public static readonly object[] ChevroletModels = new object[]
   {
       "Captiva",
       "Blazer",
       "Camaro",
       "Corvette",
       "Impala",
       "Malibu",
       "Cruze",
       "Volt",
       "Sonic",
       "Trax",
       "Equinox",
       "Traverse",
       "Tahoe",
       "Colorado",
       "Silverado",
       "Lanos",
   };
    }
}

